#Grafana
- name: Adding Grafana APT Repository
  shell: 
    sudo apt install -y gnupg2 curl software-properties-common
    curl -fsSL https://packages.grafana.com/gpg.key|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/grafana.gpg

- name: Install Grafana APT Repository
  shell: 
    sudo add-apt-repository "deb https://packages.grafana.com/oss/deb stable main"

- name: Installing Grafana 
  apt:
    name:
      - grafana
    state: latest

- name: Start Grafana Service
  shell: 
    sudo systemctl enable --now grafana-server

- name: Open port 3000
  shell: 
    sudo ufw allow 3000/tcp

#Prometheus
- name: Installing Promethues and other packages
  tags: Ubuntu_packs
  apt:
    name:
      - apache2
      - prometheus
    state: latest

- name: Open port 9090
  shell: 
    sudo ufw allow 9090/tcp

- name: Restart Apache2 Service
  service:
    name: apache2
    state: restarted
    enabled: true

- name: Restart Prometheus Service
  service:
    name: prometheus
    state: restarted
    enabled: true

#InfluxDB
- name: Import InfluxDB GPG signing key
  apt_key: url=https://repos.influxdata.com/influxdb.key state=present

- name: Add InfluxDB repository
  apt_repository: repo='deb https://repos.influxdata.com/ubuntu trusty stable' state=present

- name: Installing Influxdb
  apt:
    name:
      - influxdb
    state: latest

- name: Modify InfluxDB hostname
  replace:
    dest=/etc/opt/influxdb/influxdb.conf
    regexp='hostname = "localhost"'
    replace='hostname = "{{ ansible_hostname }}"'
    backup=yes

- name: Restart and Enable Influxdb Service
  service:
    name: influxdb
    state: restarted
    enabled: true
