- name: Install HTTPD, Mariadb and PHP
  dnf:
    name:
      - httpd
      - mariadb-server
      - php
      - php-common
      - php-opcache
      - php-mycrypt
      - php-cli
      - php-gd
      - php-curl
      - php-mysqlnd

- name: Enable and Restart HTTPD Service
  service:
    name: httpd
    state: restarted
    enabled: true

- name: Enable and Restart Mariadb Service
  service:
    name: mariadb
    state: restarted
    enabled: true
